[project]
dependencies = [
  "keras>=3.13.0",
  "loguru>=0.7.3",
  "matplotlib>=3.10.8",
  "numpy>=2.4.0",
  "pillow>=12.1.0",
  "torch>=2.9.1",
  "torchaudio>=2.9.1",
  "torchvision>=0.24.1",
  "tqdm>=4.67.1",
]
description = ""
name = "3D_Gaussian_Splatting_for_Real_Time_Radiance_Field_Rendering"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"
